### ISSUE TITLE
Full example with connected Component

### ISSUE THREAD

**Issue by cristiam86** [trialspark/enzyme-context#33]
**Describe the bug**
Following the guides from the documentation about the enzyme-context-redux plugin ([here](https://trialspark.gitbook.io/enzyme-context/official-plugins/enzyme-context-redux)) I miss an examle of the component to be tested. In my project I want to test a connected component but always get the following error when try to shallow it:
**Invariant Violation: Could not find "store" in the context of "Connect(ReduxExampleHeader)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(ReduxExampleHeader) in connect options.**

**To Reproduce**
1. Follow the steps on the [documentation](https://trialspark.gitbook.io/enzyme-context/official-plugins/enzyme-context-redux)
2. Try to sallow your component: `shallow(<ReduxExampleHeader />)`
3. See error

**Expected behavior**
The component should be rendered 

**System information**
OS Version: Windows 10 pro, 
Node Version: v10.15.3
Enzyme Version: 3.10.0
React Version:16.9.0
React Redux: 7.1.1
Redux: 4.0.4

**Comment by minznerjosh** [comment]
Unfortunately this is because the latest version of `react-redux` uses the [`useContext` hook](https://reactjs.org/docs/hooks-reference.html#usecontext) under the hood. `useContext` is currently not supported by enzyme `shallow`, largely due to limitations with the react shallow renderer.

Downgrading to `react-redux@v5.x` would allow use of `shallow` again. Alternatively, you could switch to `mount` which _does_ support `useContext`.

Here's the relevant `enzyme` issue: https://github.com/airbnb/enzyme/issues/2176

**Comment by cristiam86** [comment]
Thanks @minznerjosh I'll let you know if I can make it work.

**Comment by naudo** [comment]
We are moving to archive this repo as we no longer support it and am closing this issue as "won't fix". 

If you're interested in maintaining this repo, please reach out!
