### ISSUE TITLE
Enzyme and react-redux. v7 issues

### ISSUE THREAD

**Issue by th3fallen** [trialspark/enzyme-context#41]
**Describe the bug**
react-redux is unable to get the store from context anymore when shallow mounted with your lib

**To Reproduce**

1. Install latest react-redux, enzyme, jest
2. attempt to run a previously passing test
3. see that it can now no longer see the redux store
4. Sob uncontrollably

**Expected behavior**
should be able to get the store from redux

**Screenshots**

**System information**
Mac OSX, 10.5, latest, latest
OS Version, Node Version, Enzyme Version, React Version, etc.

**Additional context**

**Comment by minznerjosh** [comment]
Sadly I think this is the same as #33. This is due to lack of support in enzyme for `useContext`, which `react-redux` uses enzymejs/enzyme#2176.

**Comment by minznerjosh** [comment]
This is, no doubt, a controversial opinion, but at TrialSpark we almost never use shallow rendering. We find that, while using `mount` makes our test suite slower, the tests are more effective at actually catching bugs because `mount` more closely replicates the way our components are used in the real world. We tend to think of our enzyme tests less as unit tests and more as integration tests. If we _do_ need to mock out a component (perhaps because it makes network requests on mount or something) we just use `jest.mock()`.

**Comment by th3fallen** [comment]
@minznerjosh thanks for the feedback, while that'll be a pain if it'll get my tests working I'll start that migration now.

**Comment by dschinkel** [comment]
related https://github.com/enzymejs/enzyme/issues/2449

**Comment by naudo** [comment]
We are moving to archive this repo as we no longer support it and am closing this issue as "won't fix". 

If you're interested in maintaining this repo, please reach out!
